[tox]
minversion = 2.5.0
envlist = py-{format,lint,unit,mypy}
skip_missing_interpreters = True

[testenv]

description =
    format: Check code formatting
    lint: Lint with ruff
    unit: Run unit tests
    mypy: Check typing with mypy

commands =
    format: ruff format --check
    lint: ruff check
    unit: pytest tests/
    mypy: mypy --install-types --non-interactive pypiano

deps =
    format: ruff
    lint: ruff
    unit: pytest
    mypy: mypy
